version: '3.8'

services:

    app:
        build:
            context: .
            dockerfile: Dockerfile
        image: laravel-image
        container_name: laravel-container
        restart: unless-stopped
        working_dir: /var/www/html
        depends_on: 
        depends_on:
            - db
        volumes:
            - .:/var/www/html
            - ./storage/logs:/var/www/html/storage/logs
            - ./storage/app:/var/www/html/storage/app
            - ./storage/framework:/var/www/html/storage/framework
            
        environment:
            - APP_NAME=Laravel
            - APP_ENV=local
            - APP_KEY=base64:5EZiZTU/TbCAMjNKiUMdGNd29CVQ2kdO56NpGlohMWo=
            - APP_DEBUG=true
            - APP_TIMEZONE=UTC
            - APP_URL=https://laraship.laraplay.fun
            
            - APP_LOCALE=en
            - APP_FALLBACK_LOCALE=en
            - APP_FAKER_LOCALE=en_US
            
            - APP_MAINTENANCE_DRIVER=file
            
            - PHP_CLI_SERVER_WORKERS=4
            
            - BCRYPT_ROUNDS=12
            
            - LOG_CHANNEL=stack
            - LOG_STACK=single
            - LOG_DEPRECATIONS_CHANNEL=null
            - LOG_LEVEL=debug
            
            - DB_CONNECTION=mysql
            - DB_HOST=db
            - DB_PORT=3306
            - DB_DATABASE=laravel
            - DB_USERNAME=laravel_user
            - DB_PASSWORD=iux4X4qBiHg7f31_
            
            - SESSION_DRIVER=database
            - SESSION_LIFETIME=120
            - SESSION_ENCRYPT=false
            - SESSION_PATH=/
            - SESSION_DOMAIN=null
            
            - BROADCAST_CONNECTION=log
            - FILESYSTEM_DISK=local
            - QUEUE_CONNECTION=database
            
            - CACHE_STORE=database
            - CACHE_PREFIX=
            
            - MEMCACHED_HOST=127.0.0.1
            
            - REDIS_CLIENT=phpredis
            - REDIS_HOST=127.0.0.1
            - REDIS_PASSWORD=null
            - REDIS_PORT=6379
            
            - MAIL_MAILER=log
            - MAIL_HOST=127.0.0.1
            - MAIL_PORT=2525
            - MAIL_USERNAME=null
            - MAIL_PASSWORD=null
            - MAIL_ENCRYPTION=null
            - MAIL_FROM_ADDRESS=hello@example.com
            - MAIL_FROM_NAME=${APP_NAME}
            
            - AWS_ACCESS_KEY_ID=
            - AWS_SECRET_ACCESS_KEY=
            - AWS_DEFAULT_REGION=us-east-1
            - AWS_BUCKET=
            - AWS_USE_PATH_STYLE_ENDPOINT=false
            
            - VITE_APP_NAME=${APP_NAME}
            
        ports:
            - "80:80"
            
        networks:
            - app-network
        command: sh -c "php artisan config:cache && php artisan route:cache && php-fpm"
        healthcheck:
            test: ["CMD-SHELL", "php artisan --version || exit 1"]
            interval: 30s
            timeout: 10s
            retries: 3
            start_period: 30s

    db:
        image: mysql:8.0
        container_name: laravel_db
        restart: unless-stopped
        command: --default-authentication-plugin=mysql_native_password
        environment:
            MYSQL_DATABASE: laravel
            MYSQL_ROOT_PASSWORD: 'BwlkLj11GNkyJ1d_'
            MYSQL_PASSWORD: 'BwlkLj11GNkyJ1d_'
            MYSQL_USER: laravel_user
        volumes:
            - mysql-data:/var/lib/mysql
            - ./docker/mysql/init:/docker-entrypoint-initdb.d
        networks:
            - app-network
        healthcheck:
            test: ["CMD", "mysqladmin", "ping", "-pBwlkLj11GNkyJ1d_"]
            interval: 10s
            timeout: 5s
            retries: 5

networks:
    app-network:
        driver: bridge

volumes:
    backups:
        driver: local
    composer-cache:
        driver: local
    
    mysql-data:
        driver: local