version: '3.8'

services:
    app:
        build:
            context: .
            dockerfile: Dockerfile
        image: laravel-app
        container_name: laravel-app
        restart: unless-stopped
        working_dir: /var/www/html
        volumes:
            - .:/var/www/html
        networks:
            - sail
        ports:
            - "80:80"
            - "443:443"
        environment:
            - APP_NAME=Laravel
            - APP_ENV=local
            - APP_KEY=base64:5EZiZTU/TbCAMjNKiUMdGNd29CVQ2kdO56NpGlohMWo=
            - APP_DEBUG=true
            - APP_TIMEZONE=UTC
            - APP_URL=https://laraship.laraplay.fun

            - APP_LOCALE=en
            - APP_FALLBACK_LOCALE=en
            - APP_FAKER_LOCALE=en_US

            - APP_MAINTENANCE_DRIVER=file


            - PHP_CLI_SERVER_WORKERS=4

            - BCRYPT_ROUNDS=12

            - LOG_CHANNEL=stack
            - LOG_STACK=single
            - LOG_DEPRECATIONS_CHANNEL=null
            - LOG_LEVEL=debug

            - DB_CONNECTION=mysql
            - DB_HOST=db
            - DB_PORT=3306
            - DB_DATABASE=laravel
            - DB_USERNAME=laravel_user
            - DB_PASSWORD=xd43or6kyggicwgp

            - SESSION_DRIVER=database
            - SESSION_LIFETIME=120
            - SESSION_ENCRYPT=false
            - SESSION_PATH=/
            - SESSION_DOMAIN=null

            - BROADCAST_CONNECTION=log
            - FILESYSTEM_DISK=local
            - QUEUE_CONNECTION=database

            - CACHE_STORE=database
            - CACHE_PREFIX=

            - MEMCACHED_HOST=127.0.0.1

            - REDIS_CLIENT=phpredis
            - REDIS_HOST=127.0.0.1
            - REDIS_PASSWORD=null
            - REDIS_PORT=6379

            - MAIL_MAILER=log
            - MAIL_HOST=127.0.0.1
            - MAIL_PORT=2525
            - MAIL_USERNAME=null
            - MAIL_PASSWORD=null
            - MAIL_ENCRYPTION=null
            - MAIL_FROM_ADDRESS="hello@example.com"
            - MAIL_FROM_NAME="${APP_NAME}"

            - AWS_ACCESS_KEY_ID=
            - AWS_SECRET_ACCESS_KEY=
            - AWS_DEFAULT_REGION=us-east-1
            - AWS_BUCKET=
            - AWS_USE_PATH_STYLE_ENDPOINT=false

            - VITE_APP_NAME="${APP_NAME}"

            - DB_HOST=mysql
            - DB_PORT=3306
            - DB_DATABASE=laravel
            - DB_USERNAME=root
            - DB_PASSWORD='uzh2jc6a1fupa5a1'
        healthcheck:
            test: ["CMD", "curl", "-f", "http://localhost"]
            interval: 30s
            timeout: 10s
            retries: 3


    mysql:
        image: mysql:8.0
        container_name: laravel-mysql
        restart: unless-stopped
        environment:
            MYSQL_ROOT_PASSWORD: 'uzh2jc6a1fupa5a1'
            MYSQL_DATABASE: laravel
        volumes:
            - mysql-data:/var/lib/mysql
        networks:
            - sail
        ports:
            - "3306:3306"
        healthcheck:
            test: ["CMD", "mysqladmin", "ping", "-p${MYSQL_ROOT_PASSWORD}"]
            retries: 3
            timeout: 5s

networks:
    sail:
        driver: bridge

volumes:
    mysql-data:
        driver: local
